modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "openlink"
version = "${version}"
displayName = "OpenLink"
authors = "MoYStudio, Terry_MC"
description = '''
OpenLink
'''
#logoFile = ""

[[dependencies.openlink]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.openlink]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

