modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/StarCarefree/OpenLink/issues"
license = "MIT"

[[mods]]
modId = "openlink"
version = "${version}"
displayName = "OpenLink"
authors = "StarCarefree, Terry_MC, zirranYa"
description = '''
Bring you a unique Minecraft Multiplayer playing experience OvO
'''
logoFile = "icon.png"

[[dependencies.openlink]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.openlink]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "CLIENT"
