modLoader = "javafml"
# Change Forge Loader Version here(version migrate)
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/StarCarefree/OpenLink/issues"
license = "MIT"

[[mods]]
modId = "openlink"
version = "${version}"
displayName = "OpenLink"
authors = "StarCarefree, Terry_MC, zirranYa"
description = '''
Bring you a unique Minecraft Multiplayer playing experience OvO
'''
logoFile = "icon.png"

[[dependencies.openlink]]
modId = "forge"
mandatory = true
# And here
versionRange = "[36,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.openlink]]
modId = "minecraft"
mandatory = true
# Change Minecraft Version here(version migrate)
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "CLIENT"
