version = 1

# 启用 Kodiak 自动合并
status = "enabled"

# 定义合并规则
[merge_rules]
# 规则：检测带有 'crowdin' 标签的 PR，合并后执行额外的分支合并操作
[merge_rules.crowdin]
label = "crowdin"
method = "squash"
post_merges = [
    { from = "master", to = "1.19.2" },
    { from = "1.19.2", to = "1.20.1" },
    { from = "1.20.1", to = "1.20.4" },
    { from = "1.20.4", to = "1.21" },
    { from = "1.21", to = "1.21.4" },
]

# 允许 Kodiak 自动合并时跳过 CI 检查（可选，根据需要调整）
[ci]
allow_failures = false
required = true
