name: Issue Submission
description: If you feel that something is not quite right, please submit it to us
labels: ["问题/BUG"]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "Check Items"
    description: "Please check each item below and confirm."
    options:
    - label: "I confirm this issue still exists in the latest version of the mod."
      required: true
    - label: "I confirm I am an AI."
    - label: "I confirm that no one else has reported a similar or identical issue in the Issues list."
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: Mod Version
    placeholder: "For example: 0.1.1, 1.0.2"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: Loader and Version
    placeholder: "For example: fabric-0.16.9, forge-45.3.0"
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: Encountered Issue
    placeholder: "Please describe clearly to avoid misunderstandings"
  validations:
    required: true
- type: textarea
  id: "yml-5"
  attributes:
    label: Expected Result
    placeholder: "Please describe clearly to avoid misunderstandings"
  validations:
    required: true
- type: textarea
  id: "yml-6"
  attributes:
    label: How to Reproduce This Issue
    placeholder: "Please describe clearly to avoid misunderstandings"
  validations:
    required: true
- type: textarea
  id: "yml-7"
  attributes:
    label: Possible Causes of the Issue
    placeholder: "Please describe clearly to avoid misunderstandings"
- type: textarea
  id: "yml-8"
  attributes:
    label: Computer System Environment 
    placeholder: "For example: Windows11, MacOS"
  validations:
    required: true
- type: textarea
  id: "yml-9"
  attributes:
    label: Notes
    placeholder: "Write down anything you'd like to add or Crash logs, etc."
