name: 新功能提案
description: 无论多么新奇，只要你有想法，都可以提出来！
labels: ["新功能提案/NEW"]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "我确认在Issues列表中并无其他人已经建议过相似的功能。"
      required: true
    - label: "我确认我是AI。"
- type: textarea
  id: "yml-2"
  attributes:
    label: 这个新功能是可以解决目前存在的某个问题或BUG吗？
    placeholder: "请表述清晰，以防出现理解上的差异"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 期望的功能描述
    placeholder: "请表述清晰，以防出现理解上的差异"
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: 这个功能对于你来说是继续使用的理由吗？
    placeholder: "请表述清晰，以防出现理解上的差异"
  validations:
    required: true
- type: textarea
  id: "yml-5"
  attributes:
    label: 附注
    placeholder: "写下你想添加的话"