name: Auto Merge Crowdin PRs

on:
  pull_request:
    branches:
      - master
    types: [closed]
    
jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /usr/share/keyrings/github.asc
          sudo apt update
          sudo apt install gh

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check if PR contains 'crowdin' label
        id: check_label
        run: |
          PR_LABELS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" | jq -r '.[].name')
          
          echo "Labels: $PR_LABELS"
          
          if [[ $PR_LABELS != *"crowdin"* ]]; then
            echo "This PR does not contain the 'crowdin' label. Exiting."
            exit 1
          fi

      - name: Merge 1.19.2 into master
        run: |
          gh pr create --base 1.19.2 --head master --title "Merge master into 1.19.2" --body "Auto merge after Crowdin update" --draft
          gh pr merge --auto

      - name: Merge 1.20.1 into 1.19.2
        run: |
          gh pr create --base 1.20.1 --head 1.19.2 --title "Merge 1.19.2 into 1.20.1" --body "Auto merge after Crowdin update" --draft
          gh pr merge --auto

      - name: Merge 1.20.4 into 1.20.1
        run: |
          gh pr create --base 1.20.4 --head 1.20.1 --title "Merge 1.20.1 into 1.20.4" --body "Auto merge after Crowdin update" --draft
          gh pr merge --auto

      - name: Merge 1.20.6 into 1.20.4
        run: |
          gh pr create --base 1.20.6 --head 1.20.4 --title "Merge 1.20.4 into 1.20.6" --body "Auto merge after Crowdin update" --draft
          gh pr merge --auto

      - name: Merge 1.21 into 1.20.6
        run: |
          gh pr create --base 1.21 --head 1.20.6 --title "Merge 1.20.6 into 1.21" --body "Auto merge after Crowdin update" --draft
          gh pr merge --auto
