name: Auto Merge Branches on Crowdin PR

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  merge-branches:
    if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'crowdin')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 配置 Git 用户
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 第一步：将 master 合并到 1.19.2
      - name: Merge master into 1.19.2
        run: |
          git checkout 1.19.2
          git pull origin 1.19.2
          git merge origin/master --no-ff -m "Merge master into 1.19.2 (automated)"
          git push origin 1.19.2

      # 第二步：将 1.19.2 合并到 1.20.1
      - name: Merge 1.19.2 into 1.20.1
        run: |
          git checkout 1.20.1
          git pull origin 1.20.1
          git merge origin/1.19.2 --no-ff -m "Merge 1.19.2 into 1.20.1 (automated)"
          git push origin 1.20.1

      # 第三步：将 1.20.1 合并到 1.20.4
      - name: Merge 1.20.1 into 1.20.4
        run: |
          git checkout 1.20.4
          git pull origin 1.20.4
          git merge origin/1.20.1 --no-ff -m "Merge 1.20.1 into 1.20.4 (automated)"
          git push origin 1.20.4

      # 第四步：将 1.20.4 合并到 1.21
      - name: Merge 1.20.4 into 1.21
        run: |
          git checkout 1.21
          git pull origin 1.21
          git merge origin/1.20.4 --no-ff -m "Merge 1.20.4 into 1.21 (automated)"
          git push origin 1.21

      # 第五步：将 1.21 合并到 1.21.4
      - name: Merge 1.21 into 1.21.4
        run: |
          git checkout 1.21.4
          git pull origin 1.21.4
          git merge origin/1.21 --no-ff -m "Merge 1.21 into 1.21.4 (automated)"
          git push origin 1.21.4