name: Build
on: [push,pull_request,workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK17
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 17
      - name: Build
        run: ./gradlew build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          path: |
            fabric/build/libs/openlink-fabric-*.jar
            forge/build/libs/openlink-forge-*.jar
            quilt/build/libs/openlink-quilt-*.jar      
