name: Build All Branches

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Zulu JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v4
        with:
          gradle-version: 8.11

      - name: Build
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          branches=("master" "1.19.2" "1.20.1" "1.20.4" "1.21" "1.21.4")
          for ((i=0; i<${#branches[@]}; i++)); do
            git checkout ${branches[i]}
            ./gradlew build
          done

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ github.ref_name }}
          path: |
            forge/build/libs/*.jar
            neoforge/build/libs/*.jar
            fabric/build/libs/*.jar
            quilt/build/libs/*.jar
            