name: Build
on: 
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  workflow_dispatch: 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read|write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      
      - name: Build
        run: ./gradlew build
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            fabric/build/libs/openlink-fabric-*.jar
            forge/build/libs/openlink-forge-*.jar
            quilt/build/libs/openlink-quilt-*.jar      
